baseURL: https://www.megabeets.net/
languageCode: en-us
title: Megabeets
theme: "PaperMod"
pluralizelisttitles: false

markup:
  goldmark:
    renderer:
      unsafe: true
  extensions:
    footnote: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


menu:
    main:
      - name: Blog
        url: /blog/
        weight: 5
      - name: Veganism x Megabeets
        url: /veganism/
        weight: 10
      - name: Community
        url: /community/
        weight: 15
      - name: GSoC
        url: /gsoc/
        weight: 20

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Megabeets
  description: 'Security Researcher | Reverse Engineer | Animal liberation activist'
  author: Megabeets
  images:
    - /images/megabeets.png
  
  header:
    title: 'Megabeets'
    imageUrl: '/images/megabeets.png'
    subtitle: 'Security Researcher | Reverse Engineer | Animal liberation activist'

  editPost: # Add a button to suggest changes by using the file path of the post to link to a edit destination.
    URL: "https://github.com/itayc0hen/website"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  ShowReadingTime: true
  ShowShareButtons: true
  comments: false
  # dark, light, auto
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  socialIcons:
    - name: twitter
      url: 'https://twitter.com/megabeets_'
    - name: github
      url: 'https://github.com/itayc0hen/website'
    
  ShowBreadCrumbs: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

